services:
  fe:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  be:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
        - ConnectionStrings__DefaultConnection=Server=db;Database=fizzbuzz;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: